CaffeeCoApp/CaffeeCoApp/Controllers/AdminOrdersController.cs
using CaffeeCoApp.Models;
using CaffeeCoApp.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Reflection.Metadata.Ecma335;

namespace CaffeeCoApp.Controllers
{
    [Authorize(Roles = "admin")]
    [Route("/Admin/Orders/{action=Index}/{id?}")]
    public class AdminOrdersController : Controller
    {
        private readonly ApplicationDbContext context;
        private readonly int pageSize = 10;

        public AdminOrdersController(ApplicationDbContext context)
        {
            this.context = context;
        }
        public IActionResult Index(int pageIndex)
        {
            IQueryable<Order> query = context.Orders.Include(o => o.Client)
                .Include(o => o.Items).OrderByDescending(o => o.Id);

            // Pagination

            if (pageIndex <= 0)
            {
                pageIndex = 1;
            }

            decimal count = query.Count();
            int totalPages = (int)Math.Ceiling(count / pageSize);

            query = query.Skip((pageIndex - 1) * pageSize).Take(pageSize);

            var orders = query.ToList();


            ViewBag.PageIndex = pageIndex;
            ViewBag.TotalPages = totalPages;
            ViewBag.Orders = orders;
            return View();
        }

        public IActionResult Detail(int id) 
        { 
            var order = context.Orders.Include(o => o.Client).Include(o => o.Items).ThenInclude(i => i.Product).FirstOrDefault(o => o.Id == id); 

            if (order == null)
            {
                return RedirectToAction("Index");
            }

            ViewBag.NumOrders = context.Orders.Where(o => o.ClientId == order.ClientId).Count();
            return View(order);
        }

        public IActionResult Edit(int id, string? shippingStatus)
        {
            string[] validStatus = { "pending", "intransit", "delivered"};
            var order = context.Orders.Find(id);
            if (order == null) {
                Console.WriteLine("Order is not found!");
                return RedirectToAction("Index");
            }
            if (shippingStatus == null) {
                Console.WriteLine("Invalid Shipping Status!");
                return RedirectToAction("Detail", new { id });
            }

            if (shippingStatus != null)
            {
                order.ShippingStatus = shippingStatus;
            }
            context.SaveChanges();
            
            return RedirectToAction("Detail", new { id });
        }
    }
}

CaffeeCoApp/CaffeeCoApp/Views/AdminOrders/Detail.cshtml
@model Order
@{
    var shippingstatus = Model.ShippingStatus;

    string statusBadge = "bg-warning text-dark";
    if (shippingstatus.Contains("pending"))
    {
        statusBadge = "bg-secondary";
    }
    else if (shippingstatus.Contains("intransit"))
    {
        statusBadge = "bg-info text-dark";
    }
    else if (shippingstatus.Contains("delivered"))
    {
        statusBadge = "bg-success text-dark";
    }

    var deliveryMethod = Model.IsPickUp ? "Pick-up" : "Delivery";
}

<h3 class="text-center mb-4">Order Details</h3>

<a class="btn btn-link" asp-controller="AdminOrders" asp-action="Index">Orders</a>

<div class="row mb-4">
    <div class="col-lg-6">
        <div class="border rounded py-3 px-4 h-100">
            <h3 class="mb-4">Order</h3>

            <div class="row mb-2 pb-2 border-bottom">
                <div class="col">Order ID</div>
                <div class="col">@Model.Id</div>
            </div>

            <div class="row mb-2 pb-2 border-bottom">
                <div class="col">Delivery Method</div>
                <div class="col">@deliveryMethod</div>
            </div>

            <div class="row mb-2 pb-2 border-bottom">
                <div class="col">Delivery Status</div>
                <div class="col"><span class="badge @statusBadge">@Model.ShippingStatus</span>
                    <a href="#" class="mx-2" data-bs-toggle="modal" data-bs-target="#editShippingStatusModal">Edit</a>
                </div>
            </div>

            <div class="row mb-2 pb-2 border-bottom">
                <div class="col">Order Date</div>
                <div class="col">@Model.CreatedAt</div>
            </div>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="border rounded py-3 px-4 h-100">
        <h3 class="mb-4">Client</h3>

            <div class="row mb-2 pb-2 border-bottom">
                <div class="col">Name</div>
                <div class="col">
                    <a asp-controller="Users"
                    asp-action="Details" asp-route-id="@Model.Client.Id">
                        @Model.Client.FirstName @Model.Client.LastName
                    </a>
                </div>
            </div>


            <div class="row mb-2 pb-2 border-bottom">
                <div class="col">Number of Orders</div>
                <div class="col">@ViewBag.NumOrders</div>
            </div>

            <div class="row mb-2 pb-2 border-bottom">
                <div class="col">Email</div>
                <div class="col">@Model.Client.Email</div>
            </div>

            <div class="row mb-2 pb-2 border-bottom">
                <div class="col">Phone</div>
                <div class="col">@Model.Client.PhoneNumber</div>
            </div>

            <div class="row mb-2 pb-2 border-bottom">
                <div class="col">Address</div>
                <div class="col">@Model.Client.Address</div>
            </div>

            <div class="row mb-2 pb-2 border-bottom">
                <div class="col">Registered Date</div>
                <div class="col">@Model.Client.CreatedAt</div>
            </div>
        </div>
    </div>
</div>

<table class="table">
    <thead>
        <tr>
            <th style="width:150px">Description</th>
            <th></th>
            <th style="width:100px">Units</th>
            <th style="width:100px">Amount</th>
            <th style="width:100px">Review</th>
        </tr>
    </thead>
    <tbody>
        @{
            decimal subtotal = 0;
            foreach (OrderItem item in Model.Items)
            {
                subtotal += item.UnitPrice * item.Quantity;
                <tr>
                    <td>
                        <img src="/products/@item.Product.ImageFileName" width="100" alt="..." />
                    </td>
                    <td>
                        <h4>@item.Product.Name</h4>
                        @item.Product.Category<br />
                        $@(item.UnitPrice)
                    </td>
                    <td>@item.Quantity</td>
                    <td>$@(item.UnitPrice * item.Quantity)</td>
                    <td>
                        @if (item.Rating == null)
                        {
                            <i class="bi bi-star text-warning">Not rated</i>
                        }
                        else
                        {
                            <i class="bi bi-star-fill text-warning">@item.Rating</i>
                        }
                    </td>
                </tr>
            }
        }

    </tbody>
</table>

<div class="ms-auto mb-3" style="width: 250px">
    <div class="row">
        <div class="col fw-bold">Subtotal</div>
        <div class="col text-end">$@subtotal</div>
    </div>
    <div class="row">
        <div class="col fw-bold">Shipping</div>
        <div class="col text-end">$0</div>
    </div>
    <div class="row">
        <div class="col fw-bold">Total</div>
        <div class="col text-end">$@subtotal</div>
    </div>
</div>



<!-- Modal -->
<div class="modal fade" id="editShippingStatusModal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Change Shipping Status</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="get" asp-controller="AdminOrders" asp-action="Edit">
                    <input type="hidden" name="id" value="@Model.Id"/>
                    <label>Shipping Status</label>
                    <select class="form-select mb-2" name="shippingStatus" asp-for="ShippingStatus">
                        <option value="pending">pending</option>
                        <option value="intransit">intransit</option>
                        <option value="delivered">delivered</option>
                    </select>
                    <button type="submit" class="btn btn-primary mt-3">Save</button>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

CaffeeCoApp/CaffeeCoApp/Views/AdminOrders/Index.cshtml
@{
}

<h3 class="text-center mb-4">List of Orders</h3>

<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Client</th>
            <th>Units</th>
            <th>Total</th>
            <th>Delivery Method</th>
            <th>Shipping Status</th>
            <th>Order Date</th>
            <th>Actions</th>
        </tr>
    </thead>

    <tbody>
        @foreach (Order order in ViewBag.Orders)
        {
            int count = 0;
            decimal total = 0;
            foreach (OrderItem item in order.Items)
            {
                count += item.Quantity;
                total += item.Quantity * item.UnitPrice;
            }
            var deliveryMethod = order.IsPickUp ? "Pick-up" : "Delivery";

            <tr>
                <td>@order.Id</td>
                <td>@(order.Client.FirstName + " " + order.Client.LastName)</td>
                <td>@count</td>
                <td>$@total</td>
                <td>@deliveryMethod</td>
                <td>
                    @{
                        var shippingstatus = @order.ShippingStatus;

                        string statusBadge = "bg-warning text-dark";
                        if (shippingstatus.Contains("pending"))
                        {
                            statusBadge = "bg-secondary";
                        }
                        else if (shippingstatus.Contains("intransit"))
                        {
                            statusBadge = "bg-info text-dark";
                        }
                        else if (shippingstatus.Contains("delivered"))
                        {
                            statusBadge = "bg-success text-dark";
                        }

                        <span class="badge @statusBadge">@order.ShippingStatus</span>
                    }
                </td>
                <td>@order.CreatedAt.ToString("MM/dd/yyyy")</td>
                <td>
                    <a class="btn btn-primary btn-sm" asp-controller="AdminOrders" asp-action="Detail" asp-route-id="@order.Id">Details</a>
                </td>
            </tr>
        }
    </tbody>
</table>


<nav>
<ul class="pagination">
    @for (int i = 1; i <= ViewBag.TotalPages; i++)
    {
        string active = "";
        if (i == ViewBag.PageIndex) active = "active";
        <li class="page-item @active">
            <a class="page-link" asp-route-pageIndex="@i">@i</a>
        </li>
    }
</ul>
</nav>